---
config:
    class:
        hideEmptyMembersBox: true
---

classDiagram
    class `components/base-object-properties-1.1.0`:::schemaComponent {
        name: string
        uuid: components/base-object-properties-1.1.0-uuid
        description: string
        extensions: object
        tags: object
        lineage: components/lineage-1.0.0
    }
    class `components/base-spatial-data-properties-1.1.0`:::schemaComponent {
        name: string*
        uuid: components/base-object-properties-1.1.0-uuid*
        description: string*
        extensions: object*
        tags: object*
        lineage: components/lineage-1.0.0*
        bounding_box: components/bounding-box-1.0.1
        coordinate_reference_system: components/crs-1.0.1
    }
    `components/base-object-properties-1.1.0` <|-- `components/base-spatial-data-properties-1.1.0`
    class `objects/drilling-campaign-1.0.0`:::schemaObject {
        name: string*
        uuid: components/base-object-properties-1.1.0-uuid*
        description: string*
        extensions: object*
        tags: object*
        lineage: components/lineage-1.0.0*
        bounding_box: components/bounding-box-1.0.1*
        coordinate_reference_system: components/crs-1.0.1*
        type: string = campaign
        distance_unit: elements/unit-length-1.0.1-unit_categories
        hole_id: components/category-data-1.0.1
        planned: objects/drilling-campaign-1.0.0-planned
        interim: objects/drilling-campaign-1.0.0-interim
    }
    `components/base-spatial-data-properties-1.1.0` <|-- `objects/drilling-campaign-1.0.0`
    `components/base-object-properties-1.1.0` *-- `components/base-object-properties-1.1.0-uuid` : ref uuid*
    `components/base-object-properties-1.1.0` *-- `components/lineage-1.0.0` : ref lineage*
    `components/base-spatial-data-properties-1.1.0` *-- `components/bounding-box-1.0.1` : ref bounding_box*
    `components/base-spatial-data-properties-1.1.0` *-- `components/crs-1.0.1` : ref coordinate_reference_system*
    `objects/drilling-campaign-1.0.0` *-- `elements/unit-length-1.0.1-unit_categories` : ref distance_unit*
    `objects/drilling-campaign-1.0.0` *-- `components/category-data-1.0.1` : ref hole_id*
    `objects/drilling-campaign-1.0.0` *-- `objects/drilling-campaign-1.0.0-planned` : ref planned*
    `objects/drilling-campaign-1.0.0` *-- `objects/drilling-campaign-1.0.0-interim` : ref interim*
    class `elements/unit-length-1.0.1-unit_categories`:::schemaImplicit {
    }
    class `objects/drilling-campaign-1.0.0-interim`:::schemaImplicit {
        collar: components/hole-collars-1.0.0
        path: components/downhole-direction-vector-1.0.0
        desurvey: components/desurvey-method-1.0.0
        collections: components/downhole-attributes-1.0.0
    }
    `objects/drilling-campaign-1.0.0-interim` *-- `components/hole-collars-1.0.0` : ref collar*
    `objects/drilling-campaign-1.0.0-interim` *-- `components/downhole-direction-vector-1.0.0` : ref path*
    `objects/drilling-campaign-1.0.0-interim` *-- `components/desurvey-method-1.0.0` : ref desurvey*
    `objects/drilling-campaign-1.0.0-interim` *-- `components/downhole-attributes-1.0.0` : ref collections*
    class `components/downhole-attributes-1.0.0`:::schemaComponent {
    }
    class `elements/float-array-md-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1
        length: integer
        width: integer
        data_type: string = float64
    }
    class `elements/float-array-3-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1*
        length: integer*
        data_type: string = float64*
        width: integer = 3
    }
    `elements/float-array-md-1.0.1` <|-- `elements/float-array-3-1.0.1`
    class `components/attribute-list-property-1.2.0`:::schemaComponent {
        attributes: components/one-of-attribute-1.2.0
    }
    class `components/downhole-direction-vector-1.0.0`:::schemaComponent {
        data: elements/binary-blob-1.0.1*
        length: integer*
        width: integer*
        data_type: string = float64*
        width: integer = 3*
        attributes: components/one-of-attribute-1.2.0*
    }
    `elements/float-array-md-1.0.1` <|-- `components/downhole-direction-vector-1.0.0`
    `elements/float-array-3-1.0.1` <|-- `components/downhole-direction-vector-1.0.0`
    `components/attribute-list-property-1.2.0` <|-- `components/downhole-direction-vector-1.0.0`
    `elements/float-array-md-1.0.1` *-- `elements/binary-blob-1.0.1` : ref data*
    `components/attribute-list-property-1.2.0` *-- `components/one-of-attribute-1.2.0` : ref attributes*
    class `components/one-of-attribute-1.2.0`:::schemaComponent {
    }
    class `elements/binary-blob-1.0.1`:::schemaElement {
    }
    class `components/locations-1.0.1`:::schemaComponent {
        coordinates: elements/float-array-3-1.0.1
    }
    class `components/hole-collars-1.0.0`:::schemaComponent {
        coordinates: elements/float-array-3-1.0.1*
        attributes: components/one-of-attribute-1.2.0*
        distances: elements/float-array-3-1.0.1
        holes: components/hole-chunks-1.0.0
    }
    `components/locations-1.0.1` <|-- `components/hole-collars-1.0.0`
    `components/attribute-list-property-1.2.0` <|-- `components/hole-collars-1.0.0`
    `components/locations-1.0.1` *-- `elements/float-array-3-1.0.1` : ref coordinates*
    `components/hole-collars-1.0.0` *-- `elements/float-array-3-1.0.1` : ref distances*
    `components/hole-collars-1.0.0` *-- `components/hole-chunks-1.0.0` : ref holes*
    class `components/hole-chunks-1.0.0`:::schemaComponent {
        data: elements/binary-blob-1.0.1
        length: integer
        width: integer = 3
        data_type: string
    }
    `components/hole-chunks-1.0.0` *-- `elements/binary-blob-1.0.1` : ref data*
    class `components/desurvey-method-1.0.0`:::schemaComponent {
    }
    class `components/base-object-properties-1.1.0-uuid`:::schemaImplicit {
    }
    class `components/category-data-1.0.1`:::schemaComponent {
        table: elements/lookup-table-1.0.1
        values: elements/integer-array-1-1.0.1
    }
    `components/category-data-1.0.1` *-- `elements/lookup-table-1.0.1` : ref table*
    `components/category-data-1.0.1` *-- `elements/integer-array-1-1.0.1` : ref values*
    class `elements/lookup-table-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1
        length: integer
        keys_data_type: string
        values_data_type: string = string
    }
    `elements/lookup-table-1.0.1` *-- `elements/binary-blob-1.0.1` : ref data*
    class `elements/integer-array-md-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1
        length: integer
        width: integer
        data_type: string
    }
    class `elements/integer-array-1-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1*
        length: integer*
        data_type: string*
        width: integer = 1
    }
    `elements/integer-array-md-1.0.1` <|-- `elements/integer-array-1-1.0.1`
    `elements/integer-array-md-1.0.1` *-- `elements/binary-blob-1.0.1` : ref data*
    class `components/bounding-box-1.0.1`:::schemaComponent {
        min_x: number
        max_x: number
        min_y: number
        max_y: number
        min_z: number
        max_z: number
    }
    class `components/lineage-1.0.0`:::schemaComponent {
        self_link: string
        events: array
    }
    class `objects/drilling-campaign-1.0.0-planned`:::schemaImplicit {
        collar: components/hole-collars-1.0.0
        path: objects/drilling-campaign-1.0.0-planned-path
        collections: components/downhole-attributes-1.0.0
    }
    `objects/drilling-campaign-1.0.0-planned` *-- `components/hole-collars-1.0.0` : ref collar*
    `objects/drilling-campaign-1.0.0-planned` *-- `objects/drilling-campaign-1.0.0-planned-path` : ref path*
    `objects/drilling-campaign-1.0.0-planned` *-- `components/downhole-attributes-1.0.0` : ref collections*
    class `objects/drilling-campaign-1.0.0-planned-path`:::schemaImplicit {
    }
    class `components/crs-1.0.1`:::schemaComponent {
    }
