---
config:
    class:
        hideEmptyMembersBox: true
---

classDiagram
    class `components/base-object-properties-1.1.0`:::schemaComponent {
        name: string
        uuid: components/base-object-properties-1.1.0-uuid
        description: string
        extensions: object
        tags: object
        lineage: components/lineage-1.0.0
    }
    class `components/base-spatial-data-properties-1.1.0`:::schemaComponent {
        name: string*
        uuid: components/base-object-properties-1.1.0-uuid*
        description: string*
        extensions: object*
        tags: object*
        lineage: components/lineage-1.0.0*
        bounding_box: components/bounding-box-1.0.1
        coordinate_reference_system: components/crs-1.0.1
    }
    `components/base-object-properties-1.1.0` <|-- `components/base-spatial-data-properties-1.1.0`
    class `objects/lineations-data-pointset-1.3.0`:::schemaObject {
        name: string*
        uuid: components/base-object-properties-1.1.0-uuid*
        description: string*
        extensions: object*
        tags: object*
        lineage: components/lineage-1.0.0*
        bounding_box: components/bounding-box-1.0.1*
        coordinate_reference_system: components/crs-1.0.1*
        locations: objects/lineations-data-pointset-1.3.0-locations
    }
    `components/base-spatial-data-properties-1.1.0` <|-- `objects/lineations-data-pointset-1.3.0`
    `components/base-object-properties-1.1.0` *-- `components/base-object-properties-1.1.0-uuid` : ref uuid*
    `components/base-object-properties-1.1.0` *-- `components/lineage-1.0.0` : ref lineage*
    `components/base-spatial-data-properties-1.1.0` *-- `components/bounding-box-1.0.1` : ref bounding_box*
    `components/base-spatial-data-properties-1.1.0` *-- `components/crs-1.0.1` : ref coordinate_reference_system*
    `objects/lineations-data-pointset-1.3.0` *-- `objects/lineations-data-pointset-1.3.0-locations` : ref locations*
    class `components/base-object-properties-1.1.0-uuid`:::schemaImplicit {
    }
    class `components/bounding-box-1.0.1`:::schemaComponent {
        min_x: number
        max_x: number
        min_y: number
        max_y: number
        min_z: number
        max_z: number
    }
    class `components/lineage-1.0.0`:::schemaComponent {
        self_link: string
        events: array
    }
    class `components/crs-1.0.1`:::schemaComponent {
    }
    class `components/locations-1.0.1`:::schemaComponent {
        coordinates: elements/float-array-3-1.0.1
    }
    class `components/lineation-data-1.0.1`:::schemaComponent {
        lineations: elements/float-array-2-1.0.1
    }
    class `components/attribute-list-property-1.2.0`:::schemaComponent {
        attributes: components/one-of-attribute-1.2.0
    }
    class `objects/lineations-data-pointset-1.3.0-locations`:::schemaImplicit {
        coordinates: elements/float-array-3-1.0.1*
        lineations: elements/float-array-2-1.0.1*
        attributes: components/one-of-attribute-1.2.0*
    }
    `components/locations-1.0.1` <|-- `objects/lineations-data-pointset-1.3.0-locations`
    `components/lineation-data-1.0.1` <|-- `objects/lineations-data-pointset-1.3.0-locations`
    `components/attribute-list-property-1.2.0` <|-- `objects/lineations-data-pointset-1.3.0-locations`
    `components/locations-1.0.1` *-- `elements/float-array-3-1.0.1` : ref coordinates*
    `components/lineation-data-1.0.1` *-- `elements/float-array-2-1.0.1` : ref lineations*
    `components/attribute-list-property-1.2.0` *-- `components/one-of-attribute-1.2.0` : ref attributes*
    class `components/one-of-attribute-1.2.0`:::schemaComponent {
    }
    class `elements/float-array-md-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1
        length: integer
        width: integer
        data_type: string = float64
    }
    class `elements/float-array-3-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1*
        length: integer*
        data_type: string = float64*
        width: integer = 3
    }
    `elements/float-array-md-1.0.1` <|-- `elements/float-array-3-1.0.1`
    `elements/float-array-md-1.0.1` *-- `elements/binary-blob-1.0.1` : ref data*
    class `elements/binary-blob-1.0.1`:::schemaElement {
    }
    class `elements/float-array-2-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1*
        length: integer*
        data_type: string = float64*
        width: integer = 2
    }
    `elements/float-array-md-1.0.1` <|-- `elements/float-array-2-1.0.1`
