---
config:
    class:
        hideEmptyMembersBox: true
---

classDiagram
    class `components/base-object-properties-1.0.1`:::schemaComponent {
        name: string
        uuid: components/base-object-properties-1.0.1-uuid
        description: string
        extensions: object
        tags: object
    }
    class `components/base-spatial-data-properties-1.0.1`:::schemaComponent {
        name: string*
        uuid: components/base-object-properties-1.0.1-uuid*
        description: string*
        extensions: object*
        tags: object*
        bounding_box: components/bounding-box-1.0.1
        coordinate_reference_system: components/crs-1.0.1
    }
    `components/base-object-properties-1.0.1` <|-- `components/base-spatial-data-properties-1.0.1`
    class `objects/magnetics-1.0.1`:::schemaObject {
        name: string*
        uuid: components/base-object-properties-1.0.1-uuid*
        description: string*
        extensions: object*
        tags: object*
        bounding_box: components/bounding-box-1.0.1*
        coordinate_reference_system: components/crs-1.0.1*
        type: string
        survey_type: string
        gradient_magnetic: objects/magnetics-1.0.1-gradient_magnetic
        base_stations: array
        magnetic_line_list: array
        qaqc_magnetic_azimuth_test_list: array
        qaqc_noise_test_list: array
    }
    `components/base-spatial-data-properties-1.0.1` <|-- `objects/magnetics-1.0.1`
    `components/base-object-properties-1.0.1` *-- `components/base-object-properties-1.0.1-uuid` : ref uuid*
    `components/base-spatial-data-properties-1.0.1` *-- `components/bounding-box-1.0.1` : ref bounding_box*
    `components/base-spatial-data-properties-1.0.1` *-- `components/crs-1.0.1` : ref coordinate_reference_system*
    `objects/magnetics-1.0.1` *-- `objects/magnetics-1.0.1-gradient_magnetic` : ref gradient_magnetic*
    class `components/base-object-properties-1.0.1-uuid`:::schemaImplicit {
    }
    class `objects/magnetics-1.0.1-gradient_magnetic`:::schemaImplicit {
        number_of_sensors: integer
        sensor_offsets: array
    }
    class `components/crs-1.0.1`:::schemaComponent {
    }
    class `components/bounding-box-1.0.1`:::schemaComponent {
        min_x: number
        max_x: number
        min_y: number
        max_y: number
        min_z: number
        max_z: number
    }
