---
config:
    class:
        hideEmptyMembersBox: true
---

classDiagram
    class `components/base-object-properties-1.1.0`:::schemaComponent {
        name: string
        uuid: components/base-object-properties-1.1.0-uuid
        description: string
        extensions: object
        tags: object
        lineage: components/lineage-1.0.0
    }
    class `components/base-spatial-data-properties-1.1.0`:::schemaComponent {
        name: string*
        uuid: components/base-object-properties-1.1.0-uuid*
        description: string*
        extensions: object*
        tags: object*
        lineage: components/lineage-1.0.0*
        bounding_box: components/bounding-box-1.0.1
        coordinate_reference_system: components/crs-1.0.1
    }
    `components/base-object-properties-1.1.0` <|-- `components/base-spatial-data-properties-1.1.0`
    class `objects/resistivity-ip-1.1.0`:::schemaObject {
        name: string*
        uuid: components/base-object-properties-1.1.0-uuid*
        description: string*
        extensions: object*
        tags: object*
        lineage: components/lineage-1.0.0*
        bounding_box: components/bounding-box-1.0.1*
        coordinate_reference_system: components/crs-1.0.1*
        number_of_dimensions: string
        number_contributing_electrodes: integer
        survey: objects/resistivity-ip-1.1.0-survey
        configuration: objects/resistivity-ip-1.1.0-configuration
        line_list: array
    }
    `components/base-spatial-data-properties-1.1.0` <|-- `objects/resistivity-ip-1.1.0`
    `components/base-object-properties-1.1.0` *-- `components/base-object-properties-1.1.0-uuid` : ref uuid*
    `components/base-object-properties-1.1.0` *-- `components/lineage-1.0.0` : ref lineage*
    `components/base-spatial-data-properties-1.1.0` *-- `components/bounding-box-1.0.1` : ref bounding_box*
    `components/base-spatial-data-properties-1.1.0` *-- `components/crs-1.0.1` : ref coordinate_reference_system*
    `objects/resistivity-ip-1.1.0` *-- `objects/resistivity-ip-1.1.0-survey` : ref survey*
    `objects/resistivity-ip-1.1.0` *-- `objects/resistivity-ip-1.1.0-configuration` : ref configuration*
    class `components/base-object-properties-1.1.0-uuid`:::schemaImplicit {
    }
    class `objects/resistivity-ip-1.1.0-configuration`:::schemaImplicit {
    }
    class `components/bounding-box-1.0.1`:::schemaComponent {
        min_x: number
        max_x: number
        min_y: number
        max_y: number
        min_z: number
        max_z: number
    }
    class `components/lineage-1.0.0`:::schemaComponent {
        self_link: string
        events: array
    }
    class `objects/resistivity-ip-1.1.0-survey`:::schemaImplicit {
    }
    class `components/crs-1.0.1`:::schemaComponent {
    }
