---
config:
    class:
        hideEmptyMembersBox: true
---

classDiagram
    class `components/base-object-properties-1.0.1`:::schemaComponent {
        name: string
        uuid: components/base-object-properties-1.0.1-uuid
        description: string
        extensions: object
        tags: object
    }
    class `components/base-spatial-data-properties-1.0.1`:::schemaComponent {
        name: string*
        uuid: components/base-object-properties-1.0.1-uuid*
        description: string*
        extensions: object*
        tags: object*
        bounding_box: components/bounding-box-1.0.1
        coordinate_reference_system: components/crs-1.0.1
    }
    `components/base-object-properties-1.0.1` <|-- `components/base-spatial-data-properties-1.0.1`
    class `objects/unstructured-tet-grid-1.0.1`:::schemaObject {
        name: string*
        uuid: components/base-object-properties-1.0.1-uuid*
        description: string*
        extensions: object*
        tags: object*
        bounding_box: components/bounding-box-1.0.1*
        coordinate_reference_system: components/crs-1.0.1*
        tetrahedra: components/tetrahedra-1.0.1
    }
    `components/base-spatial-data-properties-1.0.1` <|-- `objects/unstructured-tet-grid-1.0.1`
    `components/base-object-properties-1.0.1` *-- `components/base-object-properties-1.0.1-uuid` : ref uuid*
    `components/base-spatial-data-properties-1.0.1` *-- `components/bounding-box-1.0.1` : ref bounding_box*
    `components/base-spatial-data-properties-1.0.1` *-- `components/crs-1.0.1` : ref coordinate_reference_system*
    `objects/unstructured-tet-grid-1.0.1` *-- `components/tetrahedra-1.0.1` : ref tetrahedra*
    class `components/base-object-properties-1.0.1-uuid`:::schemaImplicit {
    }
    class `components/crs-1.0.1`:::schemaComponent {
    }
    class `components/tetrahedra-1.0.1`:::schemaComponent {
        vertices: components/tetrahedra-1.0.1-vertices
        indices: components/tetrahedra-1.0.1-indices
    }
    `components/tetrahedra-1.0.1` *-- `components/tetrahedra-1.0.1-vertices` : ref vertices*
    `components/tetrahedra-1.0.1` *-- `components/tetrahedra-1.0.1-indices` : ref indices*
    class `elements/index-array-4-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1
        length: integer
        width: integer = 4
        data_type: string = uint64
    }
    class `components/attribute-list-property-1.0.1`:::schemaComponent {
        attributes: components/one-of-attribute-1.0.1
    }
    class `components/tetrahedra-1.0.1-indices`:::schemaImplicit {
        data: elements/binary-blob-1.0.1*
        length: integer*
        width: integer = 4*
        data_type: string = uint64*
        attributes: components/one-of-attribute-1.0.1*
    }
    `elements/index-array-4-1.0.1` <|-- `components/tetrahedra-1.0.1-indices`
    `components/attribute-list-property-1.0.1` <|-- `components/tetrahedra-1.0.1-indices`
    `elements/index-array-4-1.0.1` *-- `elements/binary-blob-1.0.1` : ref data*
    `components/attribute-list-property-1.0.1` *-- `components/one-of-attribute-1.0.1` : ref attributes*
    class `components/one-of-attribute-1.0.1`:::schemaComponent {
    }
    class `elements/binary-blob-1.0.1`:::schemaElement {
    }
    class `elements/float-array-md-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1
        length: integer
        width: integer
        data_type: string = float64
    }
    class `elements/float-array-3-1.0.1`:::schemaElement {
        data: elements/binary-blob-1.0.1*
        length: integer*
        data_type: string = float64*
        width: integer = 3
    }
    `elements/float-array-md-1.0.1` <|-- `elements/float-array-3-1.0.1`
    class `components/tetrahedra-1.0.1-vertices`:::schemaImplicit {
        data: elements/binary-blob-1.0.1*
        length: integer*
        width: integer*
        data_type: string = float64*
        width: integer = 3*
        attributes: components/one-of-attribute-1.0.1*
    }
    `elements/float-array-md-1.0.1` <|-- `components/tetrahedra-1.0.1-vertices`
    `elements/float-array-3-1.0.1` <|-- `components/tetrahedra-1.0.1-vertices`
    `components/attribute-list-property-1.0.1` <|-- `components/tetrahedra-1.0.1-vertices`
    `elements/float-array-md-1.0.1` *-- `elements/binary-blob-1.0.1` : ref data*
    class `components/bounding-box-1.0.1`:::schemaComponent {
        min_x: number
        max_x: number
        min_y: number
        max_y: number
        min_z: number
        max_z: number
    }
